server:
  port: 5000
spring:
  application:
    name: api-geteway
zuul:
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
  routes:
    hello-service:
      path: /helloworld/**
      serviceId: hello-service
   
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 60000
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  