server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      
      
security:
  oauth2:
    client:
      client-id: secret-key
      client-secret: secret-value
      access-token-uri: http://localhost:8043/oauth/token
      user-authorization-uri: http://localhost:8043/oauth/authorize
    resource:
      user-info-uri: http://localhost:8043/user/me